// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeslaMall.Server.DAL.Context;

#nullable disable

namespace TeslaMall.Server.Migrations
{
    [DbContext(typeof(TeslaMallContext))]
    [Migration("20240225062839_CarDbConfiguration")]
    partial class CarDbConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeslaMall.Server.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RentalLocations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1c"),
                            LocationDescription = "Sunny airport welcoming any visitors to join great vacation!",
                            LocationName = "Palma Airport"
                        },
                        new
                        {
                            Id = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1a"),
                            LocationDescription = "City center buzzing with life and music. Worth checking out!",
                            LocationName = "Palma City Center"
                        },
                        new
                        {
                            Id = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1b"),
                            LocationDescription = "Best coctails, parties and company. Don't wait and go!",
                            LocationName = "Alcudia"
                        },
                        new
                        {
                            Id = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1d"),
                            LocationDescription = "Sandy beach, full sun and relax. Rent a car and go!",
                            LocationName = "Manacor"
                        });
                });

            modelBuilder.Entity("TeslaMall.Server.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReservationConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReservationPaid")
                        .HasColumnType("bit");

                    b.Property<Guid>("RentedCarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ReservationCosts")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.ReservationPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelatedReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReservationEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RelatedReservationId")
                        .IsUnique();

                    b.ToTable("ReservationPeriods");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.TeslaCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentCarStatus")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedLocationId");

                    b.HasIndex("RelatedReservationId")
                        .IsUnique()
                        .HasFilter("[RelatedReservationId] IS NOT NULL");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82a4cc83-e2c9-45be-be32-2db6ca3b1271"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1c")
                        },
                        new
                        {
                            Id = new Guid("5926dc10-3ca7-4b39-97b2-b75508726d87"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1c")
                        },
                        new
                        {
                            Id = new Guid("c7285935-db01-477d-b19a-2ff89238c154"),
                            CurrentCarStatus = 1,
                            ModelName = "Model X",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1c")
                        },
                        new
                        {
                            Id = new Guid("4e2c5039-1855-4209-8322-b089b0054b44"),
                            CurrentCarStatus = 1,
                            ModelName = "Model Y",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1a")
                        },
                        new
                        {
                            Id = new Guid("554f0f4f-b987-494b-b04a-8cfc980032fa"),
                            CurrentCarStatus = 1,
                            ModelName = "Model Y",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1a")
                        },
                        new
                        {
                            Id = new Guid("9484e99c-a1f0-4532-9302-e2ee111b7485"),
                            CurrentCarStatus = 1,
                            ModelName = "Model X",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1a")
                        },
                        new
                        {
                            Id = new Guid("03339d77-ac85-4fd1-b16f-8b9462476c0d"),
                            CurrentCarStatus = 1,
                            ModelName = "Model Y",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1b")
                        },
                        new
                        {
                            Id = new Guid("da7b19b5-c5f1-416b-b638-2ebb98462069"),
                            CurrentCarStatus = 1,
                            ModelName = "Model 3",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1b")
                        },
                        new
                        {
                            Id = new Guid("ace6624f-804f-4ecf-a17f-0afc514f22b0"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1b")
                        },
                        new
                        {
                            Id = new Guid("a903cf31-b367-4cf9-9ea1-9e7dd13cec02"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1d")
                        },
                        new
                        {
                            Id = new Guid("96fa3765-01d3-4314-9fd4-488ee830bc4e"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1d")
                        },
                        new
                        {
                            Id = new Guid("5cd8ab11-3ade-4ae0-b5ff-e181f2a99962"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1d")
                        });
                });

            modelBuilder.Entity("TeslaMall.Server.Models.UserReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RelatedReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReservationCode")
                        .HasColumnType("int");

                    b.Property<string>("ReservationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RelatedReservationId");

                    b.ToTable("UserReservations");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.ReservationPeriod", b =>
                {
                    b.HasOne("TeslaMall.Server.Models.Reservation", "RelatedReservation")
                        .WithOne("ReservationPeriod")
                        .HasForeignKey("TeslaMall.Server.Models.ReservationPeriod", "RelatedReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedReservation");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.TeslaCar", b =>
                {
                    b.HasOne("TeslaMall.Server.Models.Location", "RelatedLocation")
                        .WithMany("CarsAtLocation")
                        .HasForeignKey("RelatedLocationId");

                    b.HasOne("TeslaMall.Server.Models.Reservation", "RelatedReservation")
                        .WithOne("RentedCar")
                        .HasForeignKey("TeslaMall.Server.Models.TeslaCar", "RelatedReservationId");

                    b.Navigation("RelatedLocation");

                    b.Navigation("RelatedReservation");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.UserReservation", b =>
                {
                    b.HasOne("TeslaMall.Server.Models.Reservation", "RelatedReservation")
                        .WithMany()
                        .HasForeignKey("RelatedReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedReservation");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.Location", b =>
                {
                    b.Navigation("CarsAtLocation");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.Reservation", b =>
                {
                    b.Navigation("RentedCar")
                        .IsRequired();

                    b.Navigation("ReservationPeriod")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
