// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeslaMall.Server.DAL.Context;

#nullable disable

namespace TeslaMall.Server.Migrations
{
    [DbContext(typeof(TeslaMallContext))]
    [Migration("20240224164026_userReservation")]
    partial class userReservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeslaMall.Server.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RentalLocations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1c"),
                            LocationDescription = "Sunny airport welcoming any visitors to join great vacation!",
                            LocationName = "Palma Airport"
                        },
                        new
                        {
                            Id = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1a"),
                            LocationDescription = "City center buzzing with life and music. Worth checking out!",
                            LocationName = "Palma City Center"
                        },
                        new
                        {
                            Id = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1b"),
                            LocationDescription = "Best coctails, parties and company. Don't wait and go!",
                            LocationName = "Alcudia"
                        },
                        new
                        {
                            Id = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1d"),
                            LocationDescription = "Sandy beach, full sun and relax. Rent a car and go!",
                            LocationName = "Manacor"
                        });
                });

            modelBuilder.Entity("TeslaMall.Server.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReservationConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReservationPaid")
                        .HasColumnType("bit");

                    b.Property<float>("ReservationCosts")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.ReservationPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelatedReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReservationEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RelatedReservationId")
                        .IsUnique();

                    b.ToTable("ReservationPeriods");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.TeslaCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentCarStatus")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedLocationId");

                    b.HasIndex("RelatedReservationId")
                        .IsUnique()
                        .HasFilter("[RelatedReservationId] IS NOT NULL");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50c71cac-0cc6-4336-b3cb-d184f20f35b4"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1c")
                        },
                        new
                        {
                            Id = new Guid("8949fd89-45e4-4c6d-ba38-830cd71a7652"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1c")
                        },
                        new
                        {
                            Id = new Guid("5935ae08-d69c-44eb-a006-f34b26990899"),
                            CurrentCarStatus = 1,
                            ModelName = "Model X",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1c")
                        },
                        new
                        {
                            Id = new Guid("662ed6bf-bc92-4462-bcd2-c30dbe84e209"),
                            CurrentCarStatus = 1,
                            ModelName = "Model Y",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1a")
                        },
                        new
                        {
                            Id = new Guid("112d9211-86c9-4ec2-8100-c4df7cd7c82f"),
                            CurrentCarStatus = 1,
                            ModelName = "Model Y",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1a")
                        },
                        new
                        {
                            Id = new Guid("bed8ea64-0bbe-4145-8ec8-4d20b199241b"),
                            CurrentCarStatus = 1,
                            ModelName = "Model X",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1a")
                        },
                        new
                        {
                            Id = new Guid("2c911726-3731-41fc-a85a-27995b1d95fa"),
                            CurrentCarStatus = 1,
                            ModelName = "Model Y",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1b")
                        },
                        new
                        {
                            Id = new Guid("a23d2c0a-33cb-4580-889a-3f401d8a74e1"),
                            CurrentCarStatus = 1,
                            ModelName = "Model 3",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1b")
                        },
                        new
                        {
                            Id = new Guid("828c981e-af80-4524-8560-5f8034007d94"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1b")
                        },
                        new
                        {
                            Id = new Guid("a616ab3e-2a3b-466a-bc9f-180fe7b65e5d"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1d")
                        },
                        new
                        {
                            Id = new Guid("973863ef-c97c-4c45-909d-47d14fa24026"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1d")
                        },
                        new
                        {
                            Id = new Guid("0e87bd38-6246-44b3-a000-3ea77342d3a9"),
                            CurrentCarStatus = 1,
                            ModelName = "Model S",
                            RelatedLocationId = new Guid("bddce424-3340-45bc-a4ef-02db33bc8c1d")
                        });
                });

            modelBuilder.Entity("TeslaMall.Server.Models.UserReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RelatedReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReservationCode")
                        .HasColumnType("int");

                    b.Property<string>("ReservationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RelatedReservationId");

                    b.ToTable("UserReservations");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.ReservationPeriod", b =>
                {
                    b.HasOne("TeslaMall.Server.Models.Reservation", "RelatedReservation")
                        .WithOne("ReservationPeriod")
                        .HasForeignKey("TeslaMall.Server.Models.ReservationPeriod", "RelatedReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedReservation");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.TeslaCar", b =>
                {
                    b.HasOne("TeslaMall.Server.Models.Location", "RelatedLocation")
                        .WithMany("CarsAtLocation")
                        .HasForeignKey("RelatedLocationId");

                    b.HasOne("TeslaMall.Server.Models.Reservation", "RelatedReservation")
                        .WithOne("RentedCar")
                        .HasForeignKey("TeslaMall.Server.Models.TeslaCar", "RelatedReservationId");

                    b.Navigation("RelatedLocation");

                    b.Navigation("RelatedReservation");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.UserReservation", b =>
                {
                    b.HasOne("TeslaMall.Server.Models.Reservation", "RelatedReservation")
                        .WithMany()
                        .HasForeignKey("RelatedReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedReservation");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.Location", b =>
                {
                    b.Navigation("CarsAtLocation");
                });

            modelBuilder.Entity("TeslaMall.Server.Models.Reservation", b =>
                {
                    b.Navigation("RentedCar")
                        .IsRequired();

                    b.Navigation("ReservationPeriod")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
